services:
  web:
    build: ./app
    ports:
      - 8081
    depends_on:
      skumodel:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8081/index.php"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 30s

  skumodel:
    build: ./app/skumodel-srv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4455/index.php"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 30s
    environment:
      - NGINX_PORT=4455
