services:
  db:
    container_name: mysql_db
    build:
      context: ./mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "--password=password"]
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 30s
  php:
    container_name: apache_php
    build:
      context: ./php
      args:
        - FLAG
    ports:
      - 80
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/"]
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 30s