services:
  db:
    build: ./mysql
    platform: linux/amd64
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--password=password", "-u", "root"]
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 30s
  web:
    build:
      context: ./app
      args:
        - FLAG
    ports:
      - 80
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=ctfuser
      - MYSQL_PASSWORD=MyPass1234
      - MYSQL_DATABASE=ctf
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 30s

